//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealexPayments.Remote.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealexPayments.Remote.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;request timestamp=&quot;20151201094345&quot; type=&quot;3ds-verifyenrolled&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///	&lt;amount currency=&quot;EUR&quot;&gt;29900&lt;/amount&gt;
        ///	&lt;card&gt;
        ///		&lt;number&gt;420000000000000000&lt;/number&gt;
        ///		&lt;expdate&gt;0119&lt;/expdate&gt;
        ///		&lt;type&gt;VISA&lt;/type&gt;
        ///		&lt;chname&gt;Joe Smith&lt;/chname&gt;
        ///	&lt;/card&gt;
        ///	&lt;sha1hash&gt;085f09727da50c2392b64894f962e7eb5050f762&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string _3ds_verify_enrolled_request_sample {
            get {
                return ResourceManager.GetString("_3ds_verify_enrolled_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///	&lt;authcode&gt;79347&lt;/authcode&gt;
        ///	&lt;result&gt;00&lt;/result&gt;
        ///	&lt;message&gt;Enrolled&lt;/message&gt;
        ///	&lt;pasref&gt;3737468273643&lt;/pasref&gt;
        ///	&lt;timetaken&gt;54564&lt;/timetaken&gt;
        ///	&lt;authtimetaken&gt;1001&lt;/authtimetaken&gt;
        ///	&lt;pareq&gt;eJxVUttygkAM/ZUdnitZFlBw4na02tE6bR0vD+0bLlHpFFDASv++u6i1&lt;/pareq&gt;
        ///	&lt;url&gt;http://myurl.com&lt;/url&gt;
        ///	&lt;enrolled&gt;Y&lt;/enrolled&gt;
        ///	&lt;xid&gt;e9dafe706f7142469c45d4877aaf5984&lt;/xid&gt;
        ///	&lt;sha1hash&gt;728cdbef90ff535ed8187 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3ds_verify_enrolled_response_sample {
            get {
                return ResourceManager.GetString("_3ds_verify_enrolled_response_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///	&lt;authcode&gt;79347&lt;/authcode&gt;
        ///	&lt;result&gt;110&lt;/result&gt;
        ///	&lt;message&gt;Not Enrolled&lt;/message&gt;
        ///	&lt;pasref&gt;3737468273643&lt;/pasref&gt;
        ///	&lt;timetaken&gt;54564&lt;/timetaken&gt;
        ///	&lt;authtimetaken&gt;1001&lt;/authtimetaken&gt;
        ///	&lt;pareq&gt;eJxVUttygkAM/ZUdnitZFlBw4na02tE6bR0vD+0bLlHpFFDASv++u6i1&lt;/pareq&gt;
        ///	&lt;url&gt;http://myurl.com&lt;/url&gt;
        ///	&lt;enrolled&gt;N&lt;/enrolled&gt;
        ///	&lt;xid&gt;e9dafe706f7142469c45d4877aaf5984&lt;/xid&gt;
        ///	&lt;sha1hash&gt;e553ff2510dec9bf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3ds_verify_enrolled_response_sample_not_enrolled {
            get {
                return ResourceManager.GetString("_3ds_verify_enrolled_response_sample_not_enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;request timestamp=&quot;20151201094345&quot; type=&quot;3ds-verifysig&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///	&lt;amount currency=&quot;EUR&quot;&gt;29900&lt;/amount&gt;
        ///	&lt;card&gt;
        ///		&lt;number&gt;420000000000000000&lt;/number&gt;
        ///		&lt;expdate&gt;0119&lt;/expdate&gt;
        ///		&lt;type&gt;VISA&lt;/type&gt;
        ///		&lt;chname&gt;Joe Smith&lt;/chname&gt;
        ///	&lt;/card&gt;
        ///	&lt;pares&gt;eJxVUttygkAM/ZUdnitZFlBw4na02tE6bR0vD+0bLlHpFFDASv++u6i1&lt;/pares&gt;
        ///	&lt;sha1hash&gt;085f09727da50c2392b64894f962e7eb5050f762&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string _3ds_verify_sig_request_sample {
            get {
                return ResourceManager.GetString("_3ds_verify_sig_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///	&lt;authcode&gt;79347&lt;/authcode&gt;
        ///	&lt;result&gt;00&lt;/result&gt;
        ///	&lt;message&gt;Authentication Successful&lt;/message&gt;
        ///	&lt;threedsecure&gt;
        ///		&lt;status&gt;Y&lt;/status&gt;
        ///		&lt;eci&gt;5&lt;/eci&gt;
        ///		&lt;xid&gt;e9dafe706f7142469c45d4877aaf5984&lt;/xid&gt;
        ///		&lt;cavv&gt;AAABASY3QHgwUVdEBTdAAAAAAAA=&lt;/cavv&gt;
        ///		&lt;algorithm&gt;1&lt;/algorithm&gt;
        ///	&lt;/threedsecure&gt;
        ///	&lt;sha1hash&gt;e5a7745da5dc32d234c3f52860132c482107e9ac&lt;/sha1hash&gt;
        ///&lt;/response&gt;.
        /// </summary>
        internal static string _3ds_verify_sig_response_sample {
            get {
                return ResourceManager.GetString("_3ds_verify_sig_response_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request timestamp=&quot;20150820154047&quot; type=&quot;auth-mobile&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;8cdbf036-73e2-44ff-bf11-eba8cab33a14&lt;/orderid&gt;
        ///    &lt;mobile&gt;apple-pay&lt;/mobile&gt;
        ///	&lt;token&gt;{&quot;version&quot;:&quot;EC_v1&quot;,&quot;data&quot;:&quot;Ft+dvmdfgnsdfnbg+zerKtkh/RWWjdfgdjhHGFHGFlkjdfgkljlkfs78678hEPnsbXZnMDy3o7qDg+iDHB0JVEjDHxjQIAPcNN1Cqdtq63nX4+VRU3eXzdo1QGqSptH6D5KW5SxZLAdnMEmCxG9vkVEdHTTlhVPddxiovAkFTBWBFTJ2uf5f2grXC/VnK0X/efAowXrhJIX1ngsGfAk3/EVRzADGH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auth_mobile_payment_request_sample {
            get {
                return ResourceManager.GetString("auth_mobile_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request timestamp=&quot;20151204145825&quot; type=&quot;credit&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;6df026a7-15d6-4b92-86e1-9f7b2b1d97c5&lt;/orderid&gt;
        ///	&lt;pasref&gt;13276780809852&lt;/pasref&gt;
        ///	&lt;authcode&gt;AP12346&lt;/authcode&gt;
        ///	&lt;amount currency=&quot;EUR&quot;&gt;3000&lt;/amount&gt;
        ///	&lt;refundhash&gt;52ed08590ab0bb6c2e5e4c9584aca0f6e9635a3a&lt;/refundhash&gt;
        ///	&lt;sha1hash&gt;c1319b2999608fcfa3e71d583627affaeb25d961&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string credit_payment_request_sample {
            get {
                return ResourceManager.GetString("credit_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request type=&quot;hold&quot; timestamp=&quot;20151204161419&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;292af5fa-6cbc-43d5-b2f0-7fd134d78d95&lt;/orderid&gt;
        ///    &lt;pasref&gt;ABC123456&lt;/pasref&gt;
        ///    &lt;sha1hash&gt;eec6d1f5dcc51a6a2d2b59af5d2cdb965806d96c&lt;/sha1hash&gt; 
        ///&lt;/request&gt;.
        /// </summary>
        internal static string hold_payment_request_sample {
            get {
                return ResourceManager.GetString("hold_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request type=&quot;otb&quot; timestamp=&quot;20151204152333&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;3be87fe9-db95-470f-ab04-b82f965f5b17&lt;/orderid&gt;
        ///    &lt;card&gt;
        ///        &lt;number&gt;420000000000000000&lt;/number&gt;
        ///        &lt;expdate&gt;0119&lt;/expdate&gt;
        ///        &lt;chname&gt;Joe Smith&lt;/chname&gt;
        ///        &lt;type&gt;VISA&lt;/type&gt;
        ///        &lt;issueno&gt;1&lt;/issueno&gt;
        ///        &lt;cvn&gt;
        ///            &lt;number&gt;123&lt;/number&gt;
        ///            &lt;presind&gt;1&lt;/presind&gt;
        ///        &lt;/cvn&gt;
        ///    &lt;/card&gt;
        ///    &lt;autose [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string otb_payment_request_sample {
            get {
                return ResourceManager.GetString("otb_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;request type=&quot;auth&quot; timestamp=&quot;20151201094345&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///    &lt;channel&gt;yourChannel&lt;/channel&gt;
        ///    &lt;amount currency=&quot;EUR&quot;&gt;29900&lt;/amount&gt;
        ///    &lt;card&gt;
        ///        &lt;number&gt;420000000000000000&lt;/number&gt;
        ///        &lt;expdate&gt;0119&lt;/expdate&gt;
        ///        &lt;chname&gt;Joe Smith&lt;/chname&gt;
        ///        &lt;type&gt;VISA&lt;/type&gt;
        ///        &lt;issueno&gt;1&lt;/issueno&gt;
        ///        &lt;cvn&gt;
        ///            &lt;number&gt;123&lt;/number&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payment_request_sample {
            get {
                return ResourceManager.GetString("payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response timestamp=&quot;20120926112654&quot;&gt; 
        ///	&lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///    &lt;result&gt;508&lt;/result&gt; 
        ///	&lt;message&gt;error message returned from system&lt;/message&gt;
        ///&lt;/response&gt;
        ///.
        /// </summary>
        internal static string payment_response_basic_error_sample {
            get {
                return ResourceManager.GetString("payment_response_basic_error_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///    &lt;result&gt;101&lt;/result&gt;
        ///    &lt;authcode&gt;79347&lt;/authcode&gt;
        ///    &lt;message&gt;Bank Error&lt;/message&gt;
        ///    &lt;pasref&gt;3737468273643&lt;/pasref&gt;
        ///    &lt;cvnresult&gt;M&lt;/cvnresult&gt;
        ///    &lt;timetaken&gt;54564&lt;/timetaken&gt;
        ///    &lt;authtimetaken&gt;1001&lt;/authtimetaken&gt;
        ///    &lt;acquirerresponse&gt;&lt;![CDATA[&lt;response&gt;test acquirer response&lt;/response&gt;]]&gt;&lt;/acquirerr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payment_response_full_error_sample {
            get {
                return ResourceManager.GetString("payment_response_full_error_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///    &lt;result&gt;00&lt;/result&gt;
        ///    &lt;authcode&gt;79347&lt;/authcode&gt;
        ///    &lt;message&gt;Successful&lt;/message&gt;
        ///    &lt;pasref&gt;3737468273643&lt;/pasref&gt;
        ///    &lt;cvnresult&gt;M&lt;/cvnresult&gt;
        ///    &lt;timetaken&gt;54564&lt;/timetaken&gt;
        ///    &lt;authtimetaken&gt;1001&lt;/authtimetaken&gt;
        ///    &lt;acquirerresponse&gt;&lt;![CDATA[&lt;response&gt;test acquirer response&lt;/response&gt;]]&gt;&lt;/acquirerre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payment_response_sample {
            get {
                return ResourceManager.GetString("payment_response_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response timestamp=&quot;20120926112654&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;ORD453-11&lt;/orderid&gt;
        ///    &lt;result&gt;00&lt;/result&gt;
        ///    &lt;authcode&gt;79347&lt;/authcode&gt;
        ///    &lt;message&gt;Successful&lt;/message&gt;
        ///    &lt;pasref&gt;3737468273643&lt;/pasref&gt;
        ///    &lt;cvnresult&gt;M&lt;/cvnresult&gt;
        ///    &lt;timetaken&gt;54564&lt;/timetaken&gt;
        ///    &lt;authtimetaken&gt;1001&lt;/authtimetaken&gt;
        ///    &lt;acquirerresponse&gt;&lt;![CDATA[&lt;response&gt;test acquirer response&lt;/response&gt;]]&gt;&lt;/acquirerre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payment_response_sample_unknown_element {
            get {
                return ResourceManager.GetString("payment_response_sample_unknown_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request timestamp=&quot;20151204145825&quot; type=&quot;rebate&quot;&gt;
        ///	&lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///	&lt;account&gt;internet&lt;/account&gt;
        ///	&lt;orderid&gt;6df026a7-15d6-4b92-86e1-9f7b2b1d97c5&lt;/orderid&gt;
        ///	&lt;pasref&gt;13276780809852&lt;/pasref&gt;
        ///	&lt;authcode&gt;AP12346&lt;/authcode&gt;
        ///	&lt;amount currency=&quot;EUR&quot;&gt;3000&lt;/amount&gt;
        ///	&lt;refundhash&gt;52ed08590ab0bb6c2e5e4c9584aca0f6e9635a3a&lt;/refundhash&gt;
        ///	&lt;sha1hash&gt;c1319b2999608fcfa3e71d583627affaeb25d961&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string rebate_payment_request_sample {
            get {
                return ResourceManager.GetString("rebate_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request type=&quot;release&quot; timestamp=&quot;20151204161419&quot;&gt;
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;292af5fa-6cbc-43d5-b2f0-7fd134d78d95&lt;/orderid&gt;
        ///    &lt;pasref&gt;ABC123456&lt;/pasref&gt;
        ///    &lt;sha1hash&gt;eec6d1f5dcc51a6a2d2b59af5d2cdb965806d96c&lt;/sha1hash&gt; 
        ///&lt;/request&gt;.
        /// </summary>
        internal static string release_payment_request_sample {
            get {
                return ResourceManager.GetString("release_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request timestamp=&quot;20151204133035&quot; type=&quot;settle&quot;&gt; 
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;e3cf94c6-f674-4f99-b4db-7541254a8767&lt;/orderid&gt;
        ///    &lt;amount currency=&quot;EUR&quot;&gt;1000&lt;/amount&gt;
        ///    &lt;pasref&gt;13276780809850&lt;/pasref&gt;
        ///    &lt;authcode&gt;AP1234&lt;/authcode&gt;
        ///    &lt;sha1hash&gt;b2e110f78803ccb377e8f3f12730e41d0cb0ed66&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string settle_payment_request_sample {
            get {
                return ResourceManager.GetString("settle_payment_request_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request timestamp=&quot;20151204142728&quot; type=&quot;void&quot;&gt; 
        ///    &lt;merchantid&gt;thestore&lt;/merchantid&gt;
        ///    &lt;account&gt;internet&lt;/account&gt;
        ///    &lt;orderid&gt;012bf34b-3ec9-4c9b-b3a5-700f2f28e67f&lt;/orderid&gt;
        ///    &lt;amount currency=&quot;EUR&quot;&gt;1000&lt;/amount&gt;
        ///    &lt;pasref&gt;13276780809851&lt;/pasref&gt;
        ///    &lt;authcode&gt;AP12345&lt;/authcode&gt;
        ///    &lt;sha1hash&gt;9f61456cce6c90dcc13281e6b95734f5b91e628f&lt;/sha1hash&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string void_payment_request_sample {
            get {
                return ResourceManager.GetString("void_payment_request_sample", resourceCulture);
            }
        }
    }
}
